# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: models.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='models.proto',
  package='example',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0cmodels.proto\x12\x07\x65xample\"*\n\x0bPlayerModel\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x05\"8\n\x0cPlayerInputs\x12\x13\n\x0bplayer_name\x18\x01 \x01(\t\x12\x13\n\x0bpressed_key\x18\x02 \x01(\x08\x62\x06proto3')
)




_PLAYERMODEL = _descriptor.Descriptor(
  name='PlayerModel',
  full_name='example.PlayerModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='example.PlayerModel.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='example.PlayerModel.score', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=25,
  serialized_end=67,
)


_PLAYERINPUTS = _descriptor.Descriptor(
  name='PlayerInputs',
  full_name='example.PlayerInputs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player_name', full_name='example.PlayerInputs.player_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pressed_key', full_name='example.PlayerInputs.pressed_key', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=125,
)

DESCRIPTOR.message_types_by_name['PlayerModel'] = _PLAYERMODEL
DESCRIPTOR.message_types_by_name['PlayerInputs'] = _PLAYERINPUTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerModel = _reflection.GeneratedProtocolMessageType('PlayerModel', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERMODEL,
  __module__ = 'models_pb2'
  # @@protoc_insertion_point(class_scope:example.PlayerModel)
  ))
_sym_db.RegisterMessage(PlayerModel)

PlayerInputs = _reflection.GeneratedProtocolMessageType('PlayerInputs', (_message.Message,), dict(
  DESCRIPTOR = _PLAYERINPUTS,
  __module__ = 'models_pb2'
  # @@protoc_insertion_point(class_scope:example.PlayerInputs)
  ))
_sym_db.RegisterMessage(PlayerInputs)


# @@protoc_insertion_point(module_scope)
